version: 0.1.1.{build}

image: Visual Studio 2017

environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true # don't send telemetry data
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # this will prevent the CLI from pre-populating the packages cache
    NUGET_XMLDOC_MODE: skip # do not extract XML documentation files

branches:
    only:
        - master # this will also run pull requests
        - /^v\d+(?:\.\d+)?$/ # releases

before_build:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

build_script:
- ps: >-
    $version_suffix = if ($env:APPVEYOR_REPO_TAG -eq "true") {""} else {"beta"}
    .\build.ps1 -ScriptArgs "-build_version='$env:APPVEYOR_BUILD_VERSION' -version_suffix='$version_suffix'"

test: off

artifacts:
- path: artifacts\*.nupkg
  name: NugetPackages

deploy:
- provider: NuGet
  server: https://www.myget.org/F/kherr9/api/v2/package
  api_key:
    secure: VyHjv3mh6Ye9UlA6ErhBp0ptFzZRJW+nK2340ewJIAOuQPoYh4rw3bpWOc+7rIV6
  artifact: NugetPackages