version: 0.0.{build}
image: Visual Studio 2017
branches:
    only:
        - master
before_build:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
build_script:
- cmd: >-
    PowerShell -Version 5.0 .\build.ps1
test: off