version: 0.0.{build}
image: Visual Studio 2017
before_build:
    - "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
build_script:
    - PowerShell -Version 5.0 .\build.ps1
test: off