version: 0.0.{build}

configuration: Release

image: Visual Studio 2017

environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true # don't send telemetry data
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # this will prevent the CLI from pre-populating the packages cache
    NUGET_XMLDOC_MODE: skip # do not extract XML documentation files

branches:
    only:
        - master # this will also run pull requests

before_build:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

build_script:
- cmd: >-
    PowerShell -Version 5.0 .\build.ps1

test: off